# Generated by Django 3.0.8 on 2020-07-24 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200723_1442'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='profile_pic',
            new_name='profile_picture',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='description',
            new_name='overview',
        ),
        migrations.AddField(
            model_name='post',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
